SELECT VARIABLE NAME, DATE, VALUE
FROM SNOWFLAKE_PUBLIC_DATA_FREE. PUBLIC_DATA_FREE. FREDDIE_MAC_HOUSING_TIMESERIES
WHERE VARIABLE_NAME = '30-Year Fixed Rate Mortgage Rate, National Average'
ORDER BY DATE DESC
LIMIT 12;