SELECT VARIABLE NAME, DATE, VALUE
FROM SNOWFLAKE_PUBLIC_DATA_FREE. PUBLIC_DATA_FREE. FINANCIAL_ECONOMIC_INDICATORS_TIMESERIES
WHERE GEO_ID = 'country/USA'
AND VARIABLE_NAME = 'CPI: All items, Monthly, 1982-84 Index Date (Seasonally adjusted)'
ORDER BY DATE DESC
LIMIT 12;