CREATE DATABASE IF NOT EXISTS ECON_AGENT_DB;
CREATE SCHEMA IF NOT EXISTS ECON_AGENT_DB.ANALYTICS;

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE DATABASE ECON_AGENT_DB;
USE SCHEMA ANALYTICS;
USE WAREHOUSE COMPUTE_WH;