USE DATABASE ECON_AGENT_DB;
USE SCHEMA ANALYTICS;
CREATE OR REPLACE DYNAMIC TABLE ECONOMIC_DASHBOARD_LIVE
    TARGET_LAG = '1 hour'
    WAREHOUSE = COMPUTE_WH
AS
SELECT
    DATE,
    MAX(CASE WHEN METRIC = 'CPI' THEN VALUE END) AS CPI,
    MAX(CASE WHEN METRIC = 'UNEMPLOYMENT_RATE' THEN VALUE END) AS UNEMPLOYMENT_RATE,
    MAX(CASE WHEN METRIC = 'MORTGAGE_RATE_30Y' THEN VALUE END) AS MORTGAGE_RATE_30Y
FROM (
    -- CPI and Unemployment from the economic indicators table
    SELECT DATE, VALUE::DOUBLE AS VALUE, 'CPI' AS METRIC
    FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.FINANCIAL_ECONOMIC_INDICATORS_TIMESERIES
    WHERE GEO_ID = 'country/USA'
        AND VARIABLE_NAME = 'CPI: All items, Monthly, 1982-84 Index Date (Seasonally adjusted)'
    UNION ALL
    SELECT DATE, VALUE::DOUBLE, 'UNEMPLOYMENT_RATE'
    FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.FINANCIAL_ECONOMIC_INDICATORS_TIMESERIES
    WHERE GEO_ID = 'country/USA'
        AND VARIABLE_NAME = 'Current Labor Force: Unemployment Rate - 20 yrs. & over, Monthly (Seasonally adjusted)'
    UNION ALL
    -- Mortgage rate from the Freddie Mac table
    SELECT DATE, VALUE::DOUBLE, 'MORTGAGE_RATE_30Y'
    FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.FREDDIE_MAC_HOUSING_TIMESERIES
    WHERE VARIABLE_NAME = '30-Year Fixed Rate Mortgage Rate, National Average'
)
GROUP BY DATE;

SELECT * FROM ECONOMIC_DASHBOARD_LIVE
ORDER BY DATE DESC
LIMIT 20;

SHOW DYNAMIC TABLES LIKE 'ECONOMIC_DASHBOARD_LIVE' IN SCHEMA ANALYTICS;