SELECT VARIABLE NAME, DATE, VALUE
FROM SNOWFLAKE_PUBLIC_DATA_FREE. PUBLIC_DATA_FREE. FINANCIAL_ECONOMIC_INDICATORS_TIMESERIES
WHERE GEO_ID = 'country/USA'
AND VARIABLE_NAME = 'Current Labor Force: Unemployment Rate - 20 yrs. & over, Monthly (Seasonally adjusted)'
ORDER BY DATE DESC
LIMIT 12;